default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: musify_development
  username: mariotmc
  password:
  host: localhost

test:
  <<: *default
  database: musify_test
  username: mariotmc
  password:
  host: localhost

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  prepared_statements: false
